Clean up code
dbmdz/imageio-jnr pull request #142
Opened 2021-06-29 09:49 UTC by bitzl

Code cleanups as suggested by IDE.

2021-06-29 10:57 UTC, jbaiter requested changes

2021-06-29 10:57 UTC, jbaiter commented on imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/OpenJpeg.java
> +  private Pointer createPointer(Path filePath) throws IOException {
Der Name sollte eher 'createOpjFileStream' sein, Pointer ist sehr unspezifisch 😅

2021-06-29 10:57 UTC, jbaiter commented on imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/lib/structs/opj_cparameters.java
> +  public final Boolean tile_size_on = new Boolean();
Diese Felder sind Teil der Public API und das finalisieren wäre ein breaking change, eher ungern momentan, evtl TODO?

2021-06-29 11:17 UTC, bitzl commented on imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/lib/structs/opj_cparameters.java
> +  public final Boolean tile_size_on = new Boolean();
Ah, übersehen, dass die public sind - die dann natürlich nicht.

2021-07-06 12:20 UTC, bitzl commented on imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/lib/structs/opj_cparameters.java
> +  public final Boolean tile_size_on = new Boolean();
Habe ich wieder Rückgängig gemacht.

2021-07-06 12:21 UTC, bitzl commented on imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/OpenJpeg.java
> +  private Pointer createPointer(Path filePath) throws IOException {
Umbannt, hat jetzt einen sprechenden Namen.

2021-07-06 12:49 UTC, stefan-it approved these changes

2021-07-06 12:51 UTC, merged